[tox]
envlist = static, {py3.9,py3.10,py3.11}-test
skipsdist = True

[testenv]
allowlist_externals = make

commands =
    static: pip install pre-commit
    static: make static

    test: pip install --pre nameko
    test: pip install --editable .[dev]
    test: make coverage
